### PR TITLE
Heuristic class created

### PR DESCRIPTION
**Pull request by chavs1997**
I created the Heuristic class. When initialized, it needs the color of the player that the heuristic is being run for. Each time a heuristic needs to be run, the CalculateHeuristic method needs to be called with the potential board as a parameter. In the game class where the sort will take place, there needs to be a calculate possible moves method that returns a list of potential boards. The sort will then use the heuristics of those boards to do its thing.

### CODE REVIEW

**Comment by scohen40** [comment]
I'm confused, so what are we sorting through? Potential moves or potential boards?

**Comment by chavs1997** [comment]
Potential Boards

**Comment by scohen40** [comment]
how do i come up with potential boards?
I'm looking through all the moves...

**Comment by scohen40** [comment]
Can you give me a play by play of how you are thinking this should work?
Because I think we have different ideas about this, and I don't want to
continue unless I am clear on where/how to use the heuristics.

**Comment by chavs1997** [comment]
I pushed my possible Moves methods inside the Game class. One returns
computer moves one returns user moves.

**Comment by scohen40** [comment]
Could you come up with the moves part and list of boards? I can prob do the
sorting part, but I think since you understand it better, it would be
faster if you do it.
I'm working on the user side in the meantime.

**Comment by chavs1997** [comment]
Sorry, I don't understand. What exactly do you want me to write?  The
methods return  a Dictionary with potential boards/ moves. The sort needs
to create a node for each on a tree with it's heuristic, and then do the
same for each level and somehow do the whole alpha beta pruning thing.

**Comment by scohen40** [comment]
An algorithm to create that dictionary of moves for the computer's turn.
once I have that I should be able to create the sort using the dictionary
and heuristics.

**Comment by chavs1997** [comment]
The algorithm for both the player and the computer are on my GitHub in my
Game class. You can copy paste into whichever class you'll be doing the
sort in.

**Pull request merged**
